### ISSUE TITLE
AvpictureFill => AvImageFillArrays

### ISSUE THREAD

**Issue by xueqing** [xueqing/goav#6]
**Describe the bug**

When try to remove deprecated api, `av_image_fill_arrays` seems not work to replace `avpicture_fill`.

**To Reproduce**
1. Go to 'example/tutorial01'
2. Remove code in line 126 and 127, use 128-131 instead
3. Run 'go build', './tutorial01 sample.mp4'

**Expected behavior**

```sh
kiki@ubuntu:~/github/goav/example/tutorial01$ go build 
kiki@ubuntu:~/github/goav/example/tutorial01$ ./tutorial01 sample.mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sample.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf53.24.2
  Duration: 00:00:05.31, start: 0.000000, bitrate: 1589 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1205 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
[swscaler @ 0xcffb00] bad dst image pointers
Writing frame 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b9152]

goroutine 1 [running]:
main.SaveFrame(0xd35140, 0x500, 0x2d0, 0x1)
        /home/kiki/github/goav/example/tutorial01/tutorial01.go:55 +0x212
main.main()
        /home/kiki/github/goav/example/tutorial01/tutorial01.go:173 +0x548
```

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Version [4.15.0-123-generic]
- FFmpeg: [4.1]

**Comment by xueqing** [comment]
#5

**Comment by xueqing** [comment]
https://github.com/xueqing/goav/commit/dd0978b8375fd6b8c848d15724a40ffd5cc68c8a
